import pytest
from httpx import ASGITransport, AsyncClient
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlalchemy.pool import NullPool

from app.core.config import settings
from app.core.database import Base, get_db
from app.main import app

# Dedicated test engine using NullPool so that no database connection is ever
# reused across event loops. This is essential for asyncpg (PostgreSQL) in CI:
# a pooled connection is bound to the loop that created it, and pytest-asyncio
# runs each test in its own function-scoped loop, which would otherwise raise
# "attached to a different loop" errors.
_connect_args: dict = {}
if settings.database_url.startswith("sqlite"):
    _connect_args["check_same_thread"] = False

test_engine = create_async_engine(
    settings.database_url,
    poolclass=NullPool,
    connect_args=_connect_args,
)
TestSessionLocal = async_sessionmaker(test_engine, expire_on_commit=False)


async def _override_get_db():
    async with TestSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


@pytest.fixture(autouse=True)
async def setup_database():
    """Recreate the schema before every test for full isolation.

    Plain ``drop_all``/``create_all`` correctly handles the native PostgreSQL
    ENUM types generated by SQLAlchemy ``Enum`` columns, so no manual type
    cleanup is required.
    """
    async with test_engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    app.dependency_overrides[get_db] = _override_get_db
    yield
    app.dependency_overrides.clear()


@pytest.fixture
async def client():
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        yield ac
